<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LPS.APS.Core\LPS.APS.Core.csproj" />
		<ProjectReference Include="..\LPS.APS.Engine\LPS.APS.Engine.csproj" />
		<ProjectReference Include="..\LPS.APS.BusinessRules\LPS.APS.BusinessRules.csproj" />
		<ProjectReference Include="..\LPS.APS.Scheduling\LPS.APS.Scheduling.csproj" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>LPS.APS.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>